### PR TITLE
[Fixed] Error in launching AVD with AMD processor

### PR DESCRIPTION
**Pull request by RutOf**
have Windows 8.1 pro with an AMD processor. I installed the Android SDK and Eclipse. It works but the problem is that when I Create AVD and launch it shows this error:

> emulator: ERROR: x86 emulation currently requires hardware acceleration!
> Please ensure Intel HAXM is properly installed and usable.
> CPU acceleration status: HAX kernel module is not installed!

I have already installed Intel Hardware_Accelerated_Execution_Manager and I have enabled Virtual modulation from the boot menu, but it's still not working.

### CODE REVIEW

**Comment by Fnoberz** [comment]
In case you don't see the package "Intel x86 emulator accelerator" under Extras, go to Tools, Options and check the "Force https://" option and relaunch the SDK Manager.

**Comment by RutOf** [comment]
I have Windows 8.1 with an Inter Core i7. Getting the same error message.

**Comment by Fnoberz** [comment]
Make sure you have installed `HAXM installer` on your SDK Manager.

**Comment by Fnoberz** [comment]
After you download it and make sure you run the setup located in: **{SDK_FOLDER}\extras\intel\Hardware_Accelerated_Execution_Manager\intelhaxm.exe**

**Comment by Fnoberz** [comment]
If you get the error "VT not supported" during the installation disable Hyper-V on windows features. You can execute this command dism.exe /Online /Disable-Feature:Microsoft-Hyper-V. You will also need "Virtualization Technology" to be enabled on your BIOS

**Comment by RutOf** [comment]
Oh Thanks

**Pull request merged**
